// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// LOGOUT
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// USER REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// GYM TRAINER LIST
export const TRAINER_LIST_REQUEST = 'TRAINER_LIST_REQUEST';
export const TRAINER_LIST_FAILURE = 'TRAINER_LIST_FAILURE';
export const TRAINER_LIST_SUCCESS = 'TRAINER_LIST_SUCCESS';

// TRAINER ADD
export const TRAINER_ADD_REQUEST = 'TRAINER_ADD_REQUEST';
export const TRAINER_ADD_FAILURE = 'TRAINER_ADD_FAILURE';
export const TRAINER_ADD_SUCCESS = 'TRAINER_ADD_SUCCESS';

// TRAINER DETAIL -> 헬스장 정보의 트레이너 리스트에서 트레이너 누르면 gymId와 트레이너 정보 저장함
export const TRAINER_DETAIL_REQUEST = 'TRAINER_DETAIL_REQUEST';
export const TRAINER_DETAIL_FAILURE = 'TRAINER_DETAIL_FAILURE';
export const TRAINER_DETAIL_SUCCESS = 'TRAINER_DETAIL_SUCCESS';

// TRAINER DELETE -> 선택 트레이너 수정
export const TRAINER_EDIT_REQUEST = 'TRAINER_EDIT_REQUEST';
export const TRAINER_EDIT_FAILURE = 'TRAINER_EDIT_FAILURE';
export const TRAINER_EDIT_SUCCESS = 'TRAINER_EDIT_SUCCESS';

// TRAINER DELETE -> 선택 트레이너 삭제
export const TRAINER_DELETE_REQUEST = 'TRAINER_DELETE_REQUEST';
export const TRAINER_DELETE_FAILURE = 'TRAINER_DELETE_FAILURE';
export const TRAINER_DELETE_SUCCESS = 'TRAINER_DELETE_SUCCESS';

// GYM TRAINER VIEW
// export const GYM_TRAINER_REQUEST = 'GYM_TRAINER_REQUEST';
// export const GYM_TRAINER_FAILURE = 'GYM_TRAINER_FAILURE';
// export const GYM_TRAINER_SUCCESS = 'GYM_TRAINER_SUCCESS';

// GYM SEARCH
export const GYM_SEARCH_REQUEST = 'GYM_SEARCH_REQUEST';
export const GYM_SEARCH_FAILURE = 'GYM_SEARCH_FAILURE';
export const GYM_SEARCH_SUCCESS = 'GYM_SEARCH_SUCCESS';

// GYM DETAIL INFO -> 메인에서 헬스장 누르면 선택한 헬스장의 정보를 넘겨줌
export const GYM_DETAIL_INFO_REQUEST = 'GYM_DETAIL_INFO_REQUEST';
export const GYM_DETAIL_INFO_FAILURE = 'GYM_DETAIL_INFO_FAILURE';
export const GYM_DETAIL_INFO_SUCCESS = 'GYM_DETAIL_INFO_SUCCESS';

// GYM REGISTER REQUEST
export const GYM_REGISTER_REQUEST = 'GYM_REGISTER_REQUEST';
export const GYM_REGISTER_SUCCESS = 'GYM_REGISTER_SUCCESS';
export const GYM_REGISTER_FAILURE = 'GYM_REGISTER_FAILURE';

// 트레이너 등록/수정 모드
export const TRAINER_EDIT_MODE = 'TRAINER_EDIT_MODE';
