// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// LOGOUT
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// USER REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// GYM TRAINER LIST
export const TRAINER_LIST_REQUEST = 'TRAINER_LIST_REQUEST';
export const TRAINER_LIST_FAILURE = 'TRAINER_LIST_FAILURE';
export const TRAINER_LIST_SUCCESS = 'TRAINER_LIST_SUCCESS';

// TRAINER ADD
export const TRAINER_ADD_REQUEST = 'TRAINER_ADD_REQUEST';
export const TRAINER_ADD_FAILURE = 'TRAINER_ADD_FAILURE';
export const TRAINER_ADD_SUCCESS = 'TRAINER_ADD_SUCCESS';

// GYM TRAINER VIEW
// export const GYM_TRAINER_REQUEST = 'GYM_TRAINER_REQUEST';
// export const GYM_TRAINER_FAILURE = 'GYM_TRAINER_FAILURE';
// export const GYM_TRAINER_SUCCESS = 'GYM_TRAINER_SUCCESS';

// GYM SEARCH
export const GYM_SEARCH_REQUEST = 'GYM_SEARCH_REQUEST';
export const GYM_SEARCH_FAILURE = 'GYM_SEARCH_FAILURE';
export const GYM_SEARCH_SUCCESS = 'GYM_SEARCH_SUCCESS';

// GYM DETAIL INFO -> 메인에서 헬스장 누르면 선택한 헬스장의 정보를 넘겨줌
export const GYM_DETAIL_INFO_REQUEST = 'GYM_DETAIL_INFO_REQUEST';
export const GYM_DETAIL_INFO_FAILURE = 'GYM_DETAIL_INFO_FAILURE';
export const GYM_DETAIL_INFO_SUCCESS = 'GYM_DETAIL_INFO_SUCCESS';
